### ISSUE TITLE
Invalid memory address...

### ISSUE THREAD

**Issue by pnunn** [mdfaizan7/go-authentication-boilerplate#3]
I can now signup and signin and am getting cookies back with access and refresh tokens.

But.. when I go to api/user/private/user with a GET request (straight after logging in with the POST request) the server blows up entirely with the following.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa40661]

goroutine 8 [running]:
github.com/pnunn/go-authentication-boilerplate/util.SecureAuth.func1(0xc00035e280, 0xc0003bfa80, 0x16)
        /home/pnunn/go/src/github.com/pnunn/go-authentication-boilerplate/util/auth.go:90 +0x101
github.com/gofiber/fiber/v2.(*App).next(0xc00031ca20, 0xc00035e280, 0x1b, 0xb4f301, 0x1)
        /home/pnunn/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.1/router.go:126 +0x1b9
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00035e280, 0xb5d2ec, 0x1b)
        /home/pnunn/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.1/ctx.go:632 +0x88
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc00035e280, 0xc0003bfa80, 0x16)
        /home/pnunn/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.1/middleware/cors/cors.go:141 +0x305
github.com/gofiber/fiber/v2.(*App).next(0xc00031ca20, 0xc00035e280, 0xc00035e280, 0x115ed260, 0x115ed26000000004)
        /home/pnunn/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.1/router.go:126 +0x1b9
github.com/gofiber/fiber/v2.(*App).handler(0xc00031ca20, 0xc00039c000)
        /home/pnunn/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.1/router.go:154 +0x11a
github.com/valyala/fasthttp.(*Server).serveConn(0xc00009f680, 0xc25600, 0xc000380398, 0x0, 0x0)
        /home/pnunn/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/server.go:2168 +0x11ac
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000304fa0, 0xc00037ff00)
        /home/pnunn/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:223 +0xc2
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000304fa0, 0xc00037ff00, 0xa7a700, 0xc00037ff00)
        /home/pnunn/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /home/pnunn/go/pkg/mod/github.com/valyala/fasthttp@v1.17.0/workerpool.go:194 +0x115
exit status 2
```
I've copied you auth.go code directly from the repo and its still blowing up.. 🤷

**Comment by mdfaizan7** [comment]
have you put the specified header with the access token in the header field?

**Comment by pnunn** [comment]
Hmm.. OK, no. I thought it was pulling the access token from the stored cookies.

What should be in the Header?

**Comment by mdfaizan7** [comment]
access_token: "value of access token"

**Comment by pnunn** [comment]
Thank you... I was trying to end it in the Autherisation block in postman, changed to the header.. and we're away... THANK YOU.
